In [2]:
import pandas as pd
import numpy as np
from datetime import datetime

In [ ]:
_list = [x for x in range(10)]

In [1]:
import random
test = [random.randint(1,100) for x in range(100)]

In [ ]:
np_test = np.array(test)

In [20]:
test = np.round(np.random.rand(100)*100,0)
## To know the data type of data stored.
## Numpy can only store one type of data

test.dtype

dtype('float64')

In [29]:
## To Create a numpy with a specific list

test = np.arange(1, 10)

To Reshape the array

In [11]:
np_test = test.reshape(4,25)

In [12]:
np_test

array([[ 56.,  74.,  88.,  66.,  84.,  96.,  52.,  46.,  50.,  22.,  63.,
         30.,  50.,  28.,  61.,  19.,   8.,   0.,  93.,  57.,  90.,  52.,
         41.,  59.,  14.],
       [ 58.,  48.,  25.,  76.,  49.,  47.,  70.,  90.,  99.,  35.,  70.,
         46.,  33.,  11.,  25.,   6.,  78., 100.,  48.,  99.,   6.,  86.,
         48.,  97.,  62.],
       [  7.,  32.,   8.,  25.,  45.,  67.,  30.,  84.,  88.,  88.,  16.,
         62.,  70.,  77.,  59.,  44.,  37.,  48.,  98.,  65.,  51.,  36.,
          5.,  11.,  92.],
       [ 41.,  82.,   8.,  46.,   8.,  72.,  42.,  96.,  38.,  26.,  72.,
         41.,  77.,  70.,  71.,  56.,  14.,  28.,  99.,  71.,  36.,  41.,
         95.,  11.,  91.]])

To flatten an array

In [14]:
np_test_flatten = np_test.flatten()
print(np_test_flatten)

[ 56.  74.  88.  66.  84.  96.  52.  46.  50.  22.  63.  30.  50.  28.
  61.  19.   8.   0.  93.  57.  90.  52.  41.  59.  14.  58.  48.  25.
  76.  49.  47.  70.  90.  99.  35.  70.  46.  33.  11.  25.   6.  78.
 100.  48.  99.   6.  86.  48.  97.  62.   7.  32.   8.  25.  45.  67.
  30.  84.  88.  88.  16.  62.  70.  77.  59.  44.  37.  48.  98.  65.
  51.  36.   5.  11.  92.  41.  82.   8.  46.   8.  72.  42.  96.  38.
  26.  72.  41.  77.  70.  71.  56.  14.  28.  99.  71.  36.  41.  95.
  11.  91.]


To Change the value in an index
To slice the data




In [15]:
test = np_test.view()
test[0,0] = 100
np_test

array([[100.,  74.,  88.,  66.,  84.,  96.,  52.,  46.,  50.,  22.,  63.,
         30.,  50.,  28.,  61.,  19.,   8.,   0.,  93.,  57.,  90.,  52.,
         41.,  59.,  14.],
       [ 58.,  48.,  25.,  76.,  49.,  47.,  70.,  90.,  99.,  35.,  70.,
         46.,  33.,  11.,  25.,   6.,  78., 100.,  48.,  99.,   6.,  86.,
         48.,  97.,  62.],
       [  7.,  32.,   8.,  25.,  45.,  67.,  30.,  84.,  88.,  88.,  16.,
         62.,  70.,  77.,  59.,  44.,  37.,  48.,  98.,  65.,  51.,  36.,
          5.,  11.,  92.],
       [ 41.,  82.,   8.,  46.,   8.,  72.,  42.,  96.,  38.,  26.,  72.,
         41.,  77.,  70.,  71.,  56.,  14.,  28.,  99.,  71.,  36.,  41.,
         95.,  11.,  91.]])

In [18]:
test = np_test.view()
test[1:2, 4:14] = np.array([x for x in range(10)])
test

array([[100.,  74.,  88.,  66.,  84.,  96.,  52.,  46.,  50.,  22.,  63.,
         30.,  50.,  28.,  61.,  19.,   8.,   0.,  93.,  57.,  90.,  52.,
         41.,  59.,  14.],
       [ 58.,  48.,  25.,  76.,   0.,   1.,   2.,   3.,   4.,   5.,   6.,
          7.,   8.,   9.,  25.,   6.,  78., 100.,  48.,  99.,   6.,  86.,
         48.,  97.,  62.],
       [  7.,  32.,   8.,  25.,  45.,  67.,  30.,  84.,  88.,  88.,  16.,
         62.,  70.,  77.,  59.,  44.,  37.,  48.,  98.,  65.,  51.,  36.,
          5.,  11.,  92.],
       [ 41.,  82.,   8.,  46.,   8.,  72.,  42.,  96.,  38.,  26.,  72.,
         41.,  77.,  70.,  71.,  56.,  14.,  28.,  99.,  71.,  36.,  41.,
         95.,  11.,  91.]])

Concatenate data along rows and columns

In [21]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

print(np.concatenate((arr1, arr2), axis=1))
print(np.concatenate((arr1, arr2), axis=0))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Search data in a numpy array

In [ ]:
_index = np.where(np_test == 100)
print(_index)
for i in range(len(_index[0])):
  print(np_test[_index[0][i], _index[1][i]])

(array([0, 1, 2]), array([ 0, 24,  3]))
100
100
100


In [27]:
#Filter Data
test[test > 50]

array([62., 77., 66., 88., 73., 62., 76., 62., 83., 97., 54., 65., 99.,
       55., 86., 83., 69., 74., 61., 61., 70., 91., 88., 73., 96., 88.,
       74., 59., 75., 56., 68., 98., 65., 53., 52., 76., 62., 81., 94.,
       69., 70., 51., 67., 57., 94., 58.])

In [32]:
#Sort

import numpy as np
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(arr)
print(np.sort(arr, axis = 1))
print(np.sort(arr, axis=0))

[[3 2 4]
 [5 0 1]]
[[2 3 4]
 [0 1 5]]
[[3 0 1]
 [5 2 4]]


In [33]:
test = [random.randint(0, 100) + random.randint(0, 100)/100 for x in range(15)]
test = np.array(test)
test

array([33.65, 43.12, 60.87, 73.14, 93.65, 25.21, 23.67, 22.09, 55.08,
       72.24, 37.07, 88.88, 73.87, 78.43, 33.74])

In [39]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)
print("sum", newarr)


newarr = np.multiply(arr1, arr2)
print(newarr)

newarr = np.subtract(arr1, arr2)
print(newarr)

newarr = np.divide(arr1, arr2)
print(newarr)

newarr = np.power(arr1, arr2)
print(newarr)

newarr = np.mod(arr1, arr2)
print(newarr)

newarr = np.dot(arr1, arr2)
print(newarr)

sum [2 4 6]
[1 4 9]
[0 0 0]
[1. 1. 1.]
[ 1  4 27]
[0 0 0]
14


operations of elements inside the arrays which shows a result

In [51]:
test = np.array([[1,2,4],[4,5,6]])

print(np.prod(test, axis = 0))
print(np.prod(test, axis = 1))

print(np.sum(test, axis = 0))
print(np.sum(test, axis = 1))

print(np.sum(test))
print(np.mean(test))
print(np.std(test))
print(np.var(test))
print(np.min(test))
print(np.max(test))

print(np.prod(test))

[ 4 10 24]
[  8 120]
[ 5  7 10]
[ 7 15]
22
3.6666666666666665
1.699673171197595
2.888888888888889
1
6
960


In [53]:
#To find all the elements in an axis
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)


test = np.array([[1,2,4,1],[4,5,6,4]])
x = np.unique(test, axis = 1)
print(x)

[1 2 3 4 5 6 7]
[[1 2 4]
 [4 5 6]]


In [ ]:
# Create a sample matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:")
print(matrix)

# Shift elements along rows (axis=1)
# Shift by 1 position to the right
shifted_rows = np.roll(matrix, shift=1, axis=1)
print("\nShifted along rows (right by 1):")
print(shifted_rows)

# Shift by -1 position up
shifted_cols_up = np.roll(matrix, shift=-1, axis=0)
print("\nShifted along columns (up by 1):")
print(shifted_cols_up)


# Shift all elements in the flattened array (default behavior)
# Shift by 2 positions
shifted_flattened = np.roll(matrix, shift=2)
print("\nShifted all elements (flattened, by 2):")
print(shifted_flattened)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shifted along rows (right by 1):
[[3 1 2]
 [6 4 5]
 [9 7 8]]

Shifted along columns (up by 1):
[[4 5 6]
 [7 8 9]
 [1 2 3]]

Shifted all elements (flattened, by 2):
[[8 9 1]
 [2 3 4]
 [5 6 7]]


In [55]:
test = np.array([[1,2,3,4],
         [4,5,6,7],
         [8,9,10,11],
         [12,13,14,15]])
print(test)

print(np.transpose(test)) #Transpose a matrix

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  4  8 12]
 [ 2  5  9 13]
 [ 3  6 10 14]
 [ 4  7 11 15]]


In [67]:
test = np.round(np.random.rand(100)*100,0)

##Removal basis Z scores
test[((test - np.mean(test))/np.std(test) > 0.05) & ((test - np.mean(test))/np.std(test) < 0.95)]

##Removal bsis IQR
q1 = np.percentile(test, 25)
q3 = np.percentile(test, 75)
iqr = (q3 - q1)
test[(test > (q1 - iqr*1.5)) & (test < (q3 + iqr*1.5))]

array([ 43.,  76.,  46.,  73., 100.,  32.,  38.,  36.,  30.,  15.,  97.,
        94.,  95.,  27.,  53.,  29.,  62.,  17.,  94.,  60.,  53.,  41.,
        59.,  26.,   6.,  68.,  57.,  86.,  31.,  62.,  16.,   6.,  21.,
        42.,  86.,  25.,   6.,  98.,  13.,  70.,  65.,  22.,  58.,  92.,
        67.,  18.,   1.,  82.,  10.,  18.,  10.,  66.,  37.,  43.,  79.,
        13.,  11.,  81.,  46.,  41.,   1.,  79.,  70.,  13.,   7.,  31.,
        71.,  86.,  21.,  52.,  55.,  70.,   8.,  76.,  21.,  76.,  14.,
        69.,  52.,  67.,  12.,  91.,  85.,  40.,  71.,  50.,  73.,  70.,
        42.,  73.,  70.,   2.,  86.,  88.,  54.,  20.,  66.,  15.,  94.,
        20.])

In [ ]:
my_array = np.array([1, 2, np.nan, 4, np.nan, 6])
np.isnan(my_array)

array([False, False,  True, False,  True, False])

In [ ]:
test = np.round(test, 0)
np.sort(test)
np.sort(-test) * -1

array([90., 87., 77., 75., 66., 62., 62., 49., 33., 33., 24., 22.,  9.,
        0.])

In [ ]:
test[len(test)-1:0:-1]

array([62., 77., 66.,  9., 22., 62.,  0., 33., 75., 90., 24., 87., 33.])

In [ ]:
broadcast, shallow copy, deep copy for numpys theoretcial scenarios