In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime

In [ ]:
_list = [x for x in range(10)]

In [ ]:
data = pd.DataFrame(_list)
data.columns = ["Data"]
data.head(n = 4)

Data
0     0
1     1
2     2
3     3

In [ ]:
data["Z_Score"] = (data["Data"] - data["Data"].mean())/data["Data"].std()

In [ ]:
data.head(n = 4)

Data   Z_Score
0     0 -1.486301
1     1 -1.156012
2     2 -0.825723
3     3 -0.495434

In [ ]:
import random
test = [random.randint(1,100) for x in range(100)]
test

[67,
 42,
 80,
 88,
 50,
 99,
 38,
 47,
 39,
 92,
 87,
 56,
 48,
 93,
 70,
 67,
 17,
 36,
 14,
 48,
 31,
 20,
 44,
 47,
 88,
 83,
 21,
 3,
 14,
 84,
 99,
 92,
 67,
 15,
 23,
 36,
 99,
 80,
 64,
 59,
 10,
 83,
 76,
 92,
 49,
 43,
 53,
 37,
 34,
 100,
 74,
 16,
 48,
 100,
 80,
 69,
 19,
 29,
 54,
 8,
 73,
 36,
 26,
 35,
 97,
 76,
 35,
 2,
 22,
 63,
 43,
 76,
 83,
 1,
 41,
 55,
 77,
 23,
 32,
 67,
 16,
 98,
 53,
 57,
 78,
 65,
 24,
 45,
 53,
 42,
 46,
 70,
 2,
 16,
 49,
 72,
 29,
 88,
 17,
 40]

In [ ]:
temp = dict()
for i in range(len(test)):
  if test[i] in temp.keys():
    temp[test[i]] = temp[test[i]] + 1
  else:
    temp[test[i]] = 1
print(temp)

{79: 3, 95: 1, 59: 5, 81: 2, 5: 1, 68: 3, 85: 3, 80: 2, 28: 1, 6: 1, 36: 2, 70: 2, 57: 1, 65: 2, 48: 5, 88: 3, 24: 1, 40: 2, 90: 3, 69: 1, 54: 1, 34: 2, 75: 1, 82: 1, 23: 1, 97: 4, 3: 1, 21: 1, 98: 1, 19: 1, 1: 2, 53: 2, 29: 1, 38: 1, 47: 2, 89: 1, 9: 1, 51: 2, 67: 3, 4: 2, 99: 1, 64: 1, 25: 2, 7: 2, 32: 2, 27: 1, 2: 1, 62: 1, 71: 2, 31: 1, 14: 1, 83: 1, 26: 2, 92: 1, 78: 1, 33: 2, 50: 1, 44: 1, 55: 1}


In [ ]:
data.loc[5,"other_method"] = None

In [ ]:
data[data["other_method"].isna()]

Data   Z_Score  other_method
5     5  0.165145           NaN

In [ ]:
test1 = pd.DataFrame({"test":test})

test
0     67
1     42
2     80
3     88
4     50
..   ...
95    72
96    29
97    88
98    17
99    40

[100 rows x 1 columns]

In [ ]:
test1['test'].value_counts().reset_index()

test  count
0     67      4
1     80      3
2     88      3
3     99      3
4     92      3
..   ...    ...
60    24      1
61    45      1
62    46      1
63    72      1
64    40      1

[65 rows x 2 columns]

In [ ]:
np_test = np.array(test)

In [ ]:
np_test = np_test.reshape(4,25)

In [ ]:
np_test

array([[ 67,  42,  80,  88,  50,  99,  38,  47,  39,  92,  87,  56,  48,
         93,  70,  67,  17,  36,  14,  48,  31,  20,  44,  47,  88],
       [ 83,  21,   3,  14,  84,  99,  92,  67,  15,  23,  36,  99,  80,
         64,  59,  10,  83,  76,  92,  49,  43,  53,  37,  34, 100],
       [ 74,  16,  48, 100,  80,  69,  19,  29,  54,   8,  73,  36,  26,
         35,  97,  76,  35,   2,  22,  63,  43,  76,  83,   1,  41],
       [ 55,  77,  23,  32,  67,  16,  98,  53,  57,  78,  65,  24,  45,
         53,  42,  46,  70,   2,  16,  49,  72,  29,  88,  17,  40]])

In [ ]:
test = np_test.view()
test[0,0] = 100
np_test

array([[100,  42,  80,  88,  50,  99,  38,  47,  39,  92,  87,  56,  48,
         93,  70,  67,  17,  36,  14,  48,  31,  20,  44,  47,  88],
       [ 83,  21,   3,  14,  84,  99,  92,  67,  15,  23,  36,  99,  80,
         64,  59,  10,  83,  76,  92,  49,  43,  53,  37,  34, 100],
       [ 74,  16,  48, 100,  80,  69,  19,  29,  54,   8,  73,  36,  26,
         35,  97,  76,  35,   2,  22,  63,  43,  76,  83,   1,  41],
       [ 55,  77,  23,  32,  67,  16,  98,  53,  57,  78,  65,  24,  45,
         53,  42,  46,  70,   2,  16,  49,  72,  29,  88,  17,  40]])

In [ ]:
for i in np_test:
  print(i[0])

100
83
74
55


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
_index = np.where(np_test == 100)
print(_index)
for i in range(len(_index[0])):
  print(np_test[_index[0][i], _index[1][i]])

(array([0, 1, 2]), array([ 0, 24,  3]))
100
100
100


In [ ]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
test = [random.randint(0, 100) + random.randint(0, 100)/100 for x in range(15)]
test = np.array(test)
test

array([50.48, 99.7 ,  6.81, 11.67, 14.45, 56.47, 82.31, 79.16,  0.51,
       12.08, 52.06, 23.3 , 97.49, 56.97, 48.  ])

In [ ]:
np.around(test, 0)

array([ 50., 100.,   7.,  12.,  14.,  56.,  82.,  79.,   1.,  12.,  52.,
        23.,  97.,  57.,  48.])

In [ ]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

[2 4 6]
12


In [ ]:
np.mean(arr1)
np.std(arr1)
np.max(arr1)
np.min(arr1)

np.int64(1)

In [ ]:
import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [ ]:
# Create a sample matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:")
print(matrix)

# Shift elements along rows (axis=1)
# Shift by 1 position to the right
shifted_rows = np.roll(matrix, shift=1, axis=1)
print("\nShifted along rows (right by 1):")
print(shifted_rows)

# Shift by -1 position up
shifted_cols_up = np.roll(matrix, shift=-1, axis=0)
print("\nShifted along columns (up by 1):")
print(shifted_cols_up)


# Shift all elements in the flattened array (default behavior)
# Shift by 2 positions
shifted_flattened = np.roll(matrix, shift=2)
print("\nShifted all elements (flattened, by 2):")
print(shifted_flattened)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shifted along rows (right by 1):
[[3 1 2]
 [6 4 5]
 [9 7 8]]

Shifted along columns (up by 1):
[[4 5 6]
 [7 8 9]
 [1 2 3]]

Shifted all elements (flattened, by 2):
[[8 9 1]
 [2 3 4]
 [5 6 7]]



Shifted along columns (up by 1):
[[4 5 6]
 [7 8 9]
 [1 2 3]]


In [ ]:
https://www.geeksforgeeks.org/numpy/numpy-interview-questions/

SyntaxError: invalid syntax (ipython-input-2064445792.py, line 1)

In [ ]:
import numpy as np
test = np.array([[1,2,3,4],
         [4,5,6,7],
         [8,9,10,11],
         [12,13,14,15]])

In [ ]:
test.shape
test.dtype

dtype('int64')

In [ ]:
np.var(test.flatten())

np.float64(18.4375)

In [ ]:
test = test.flatten()
np.percentile(test, 0.25)
test[test < np.percentile(test, 0.25)]

array([1])

In [ ]:
my_array = np.array([1, 2, np.nan, 4, np.nan, 6])
np.isnan(my_array)

array([False, False,  True, False,  True, False])

In [ ]:
np.transpose(test)

array([[ 1,  4,  8, 12],
       [ 2,  5,  9, 13],
       [ 3,  6, 10, 14],
       [ 4,  7, 11, 15]])

In [ ]:
test = np.random.rand(14) * 100

In [ ]:
test = np.round(test, 0)
np.sort(test)
np.sort(-test) * -1

array([90., 87., 77., 75., 66., 62., 62., 49., 33., 33., 24., 22.,  9.,
        0.])

In [ ]:
test[len(test)-1:0:-1]

array([62., 77., 66.,  9., 22., 62.,  0., 33., 75., 90., 24., 87., 33.])

In [ ]:
broadcast, shallow copy, deep copy for numpys theoretcial scenarios